# -*- coding: utf-8 -*-
# PastVision
# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LandscapeTabs(QtWidgets.QTabWidget):
    def __init__(self, parent) -> None:
        super().__init__(parent)
        self.setup()

    def setup(self):
        self.landscapes = dict()
        self.setTabPosition(QtWidgets.QTabWidget.North)
        self.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.setElideMode(QtCore.Qt.ElideNone)
        self.setUsesScrollButtons(True)
        self.setTabsClosable(True)
        self.setObjectName("landscapeTabs")
        self.tabCloseRequested.connect(self.removeLandscape)

    def addLandscape(self, landscape_name: str):
        tab = Landscape(name=landscape_name)
        self.addTab(tab, "")
        self.setTabText(self.indexOf(
            tab), QtCore.QCoreApplication.translate("MainWin", landscape_name))
        self.setTabToolTip(self.indexOf(
            tab), QtCore.QCoreApplication.translate("MainWin", "Double click to rename"))
        self.landscapes[landscape_name] = tab

    def removeLandscape(self, index):
        dlg = QtWidgets.QMessageBox(self)
        dlg.setWindowTitle("Delete Confirmation")
        dlg.setText(f"Delete {self.tabText(index)} landscape?")
        dlg.setStandardButtons(QtWidgets.QMessageBox.Yes |
                               QtWidgets.QMessageBox.No)
        dlg.setIcon(QtWidgets.QMessageBox.Critical)
        button = dlg.exec()

        if button == QtWidgets.QMessageBox.Yes:
            # index = self.indexOf(self.landscapes[landscape_name])
            widget = self.widget(index)
            if widget is not None:
                widget.deleteLater()
            self.removeTab(index)


class Landscape(QtWidgets.QWidget):
    def __init__(self, name: str) -> None:
        super().__init__()
        self.name = name
        self.setup()

    def setup(self):
        self.setObjectName(self.name)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.hostnamesField = QtWidgets.QTextEdit(self)
        self.hostnamesField.setObjectName("hostnamesField")
        self.gridLayout.addWidget(self.hostnamesField, 1, 0, 1, 1)
        self.sessionNamePreviewList = QtWidgets.QListWidget(self)
        self.sessionNamePreviewList.setEnabled(True)
        self.sessionNamePreviewList.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sessionNamePreviewList.setObjectName("sessionNamePreviewList")
        self.gridLayout.addWidget(self.sessionNamePreviewList, 1, 1, 1, 1)
        self.labelHostnames = QtWidgets.QLabel(self)
        self.labelHostnames.setObjectName("labelHostnames")
        self.gridLayout.addWidget(self.labelHostnames, 0, 0, 1, 1)
        self.labelPreview = QtWidgets.QLabel(self)
        self.labelPreview.setObjectName("labelPreview")
        self.gridLayout.addWidget(self.labelPreview, 0, 1, 1, 1)
        self.labelHostnames.setText(
            QtCore.QCoreApplication.translate("MainWin", "Hostnames:"))
        self.labelPreview.setText(
            QtCore.QCoreApplication.translate("MainWin", "Preview:"))


class Ui_MainWin(object):
    def setupUi(self, MainWin: QtWidgets.QWidget):
        MainWin.setObjectName("MainWin")
        MainWin.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWin.resize(563, 440)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWin.sizePolicy().hasHeightForWidth())
        MainWin.setSizePolicy(sizePolicy)
        MainWin.setMinimumSize(QtCore.QSize(563, 440))
        MainWin.setMaximumSize(QtCore.QSize(563, 440))
        MainWin.setAutoFillBackground(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(MainWin)
        self.label.setObjectName("label")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.usernameField = QtWidgets.QLineEdit(MainWin)
        self.usernameField.setObjectName("usernameField")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.usernameField)
        self.label_2 = QtWidgets.QLabel(MainWin)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.keyField = QtWidgets.QLineEdit(MainWin)
        self.keyField.setObjectName("keyField")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.keyField)
        self.label_3 = QtWidgets.QLabel(MainWin)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.formatField = QtWidgets.QLineEdit(MainWin)
        self.formatField.setObjectName("formatField")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.formatField)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(MainWin)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadServersBtn = QtWidgets.QPushButton(MainWin)
        self.loadServersBtn.setObjectName("loadServersBtn")
        self.horizontalLayout.addWidget(self.loadServersBtn)
        self.addLandscapeBtn = QtWidgets.QPushButton(MainWin)
        self.addLandscapeBtn.setToolTipDuration(-1)
        self.addLandscapeBtn.setObjectName("addLandscapeBtn")
        self.horizontalLayout.addWidget(self.addLandscapeBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.landscapeTabs = LandscapeTabs(MainWin)
        # tab
        for i in ['NIE', 'MDG', 'DSW']:
            self.landscapeTabs.addLandscape(i)

        self.verticalLayout.addWidget(self.landscapeTabs)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.exportBtn = QtWidgets.QPushButton(MainWin)
        self.exportBtn.setObjectName("exportBtn")
        self.horizontalLayout_4.addWidget(self.exportBtn)
        self.addToPuttyBtn = QtWidgets.QPushButton(MainWin)
        self.addToPuttyBtn.setObjectName("addToPuttyBtn")
        self.horizontalLayout_4.addWidget(self.addToPuttyBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(MainWin)
        self.landscapeTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        MainWin.setWindowTitle(QtCore.QCoreApplication.translate(
            "MainWin", "PuttyServerAdder"))
        self.label.setText(
            QtCore.QCoreApplication.translate("MainWin", "Username "))
        self.usernameField.setToolTip(QtCore.QCoreApplication.translate(
            "MainWin", "Your username in os level of the servers to be added"))
        self.label_2.setText(QtCore.QCoreApplication.translate(
            "MainWin", "PrivateKey Path"))
        self.keyField.setToolTip(QtCore.QCoreApplication.translate(
            "MainWin", "Your putty private key (*.ppk) file path on the Jump Server"))
        self.label_3.setText(QtCore.QCoreApplication.translate(
            "MainWin", "Session Name Format"))
        self.label_4.setText(
            QtCore.QCoreApplication.translate("MainWin", "Landscapes:"))
        self.loadServersBtn.setToolTip(QtCore.QCoreApplication.translate(
            "MainWin", "Load landscapes from properly fromatted server list"))
        self.loadServersBtn.setText(
            QtCore.QCoreApplication.translate("MainWin", "Load From File"))
        self.addLandscapeBtn.setToolTip(QtCore.QCoreApplication.translate(
            "MainWin", "Add landscape tab manually"))
        self.addLandscapeBtn.setText(
            QtCore.QCoreApplication.translate("MainWin", "Add Landscape"))
        self.exportBtn.setText(QtCore.QCoreApplication.translate(
            "MainWin", "Export .reg file"))
        self.addToPuttyBtn.setText(
            QtCore.QCoreApplication.translate("MainWin", "Add to Putty"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    MainWin = QtWidgets.QWidget()
    ui = Ui_MainWin()
    ui.setupUi(MainWin)
    MainWin.show()
    sys.exit(app.exec_())
